sidebar:
  - identifier: home
    name: Home
    pageRef: /
    weight: 10
  - identifier: projekt
    name: Projekt
    pageRef: /projekt
    weight: 20
  - identifier: team
    name: Team
    pageRef: /team
    weight: 30
  - identifier: news
    name: News
    pageRef: /news
    weight: 40
  - identifier: github
    name: GitHub
    url: "https://github.com/Turboleaf-Technology"
    weight: 50
  - identifier: impressum
    name: Impressum
    pageRef: /impressum
    weight: 60